import type { Brand, VehicleType } from "@/lib/constants";

// Fallback brands when API is unavailable
export const FALLBACK_BRANDS: Record<VehicleType, Brand[]> = {
  carros: [
    { codigo: "59", nome: "VW - VolksWagen" },
    { codigo: "25", nome: "FIAT" },
    { codigo: "22", nome: "CHEVROLET" },
    { codigo: "56", nome: "TOYOTA" },
    { codigo: "26", nome: "FORD" },
    { codigo: "29", nome: "HONDA" },
    { codigo: "32", nome: "HYUNDAI" },
    { codigo: "43", nome: "RENAULT" },
    { codigo: "36", nome: "JEEP" },
    { codigo: "40", nome: "NISSAN" },
    { codigo: "39", nome: "MITSUBISHI" },
    { codigo: "6", nome: "AUDI" },
    { codigo: "7", nome: "BMW" },
    { codigo: "38", nome: "MERCEDES-BENZ" },
    { codigo: "41", nome: "PEUGEOT" },
    { codigo: "21", nome: "CITROEN" },
    { codigo: "37", nome: "KIA" },
    { codigo: "48", nome: "SUZUKI" },
    { codigo: "18", nome: "CHERY" },
    { codigo: "102", nome: "BYD" },
    { codigo: "171", nome: "RAM" },
    { codigo: "51", nome: "TROLLER" },
  ],
  motos: [
    { codigo: "60", nome: "HONDA" },
    { codigo: "119", nome: "YAMAHA" },
    { codigo: "109", nome: "SUZUKI" },
    { codigo: "67", nome: "KAWASAKI" },
    { codigo: "50", nome: "DAFRA" },
    { codigo: "101", nome: "SHINERAY" },
    { codigo: "27", nome: "BMW" },
    { codigo: "73", nome: "TRIUMPH" },
    { codigo: "59", nome: "HARLEY-DAVIDSON" },
    { codigo: "53", nome: "DUCATI" },
  ],
  caminhoes: [
    { codigo: "114", nome: "VOLVO" },
    { codigo: "103", nome: "SCANIA" },
    { codigo: "102", nome: "MERCEDES-BENZ" },
    { codigo: "111", nome: "VW - VOLKSWAGEN" },
    { codigo: "101", nome: "IVECO" },
    { codigo: "116", nome: "DAF" },
    { codigo: "104", nome: "FORD" },
  ],
};
