// Fallback data for when FIPE API is unavailable
// Contains all brands from the official FIPE table
// Models are not included here as there are thousands - they require API access

import { Brand, VehicleType } from './constants';

export const FALLBACK_BRANDS: Record<VehicleType, Brand[]> = {
  carros: [
    { codigo: "1", nome: "Acura" },
    { codigo: "2", nome: "Agrale" },
    { codigo: "3", nome: "Alfa Romeo" },
    { codigo: "4", nome: "AM Gen" },
    { codigo: "5", nome: "Asia Motors" },
    { codigo: "189", nome: "ASTON MARTIN" },
    { codigo: "6", nome: "Audi" },
    { codigo: "207", nome: "Baby" },
    { codigo: "7", nome: "BMW" },
    { codigo: "8", nome: "BRM" },
    { codigo: "123", nome: "Bugre" },
    { codigo: "238", nome: "BYD" },
    { codigo: "236", nome: "CAB Motors" },
    { codigo: "10", nome: "Cadillac" },
    { codigo: "245", nome: "Caoa Chery" },
    { codigo: "161", nome: "Caoa Chery/Chery" },
    { codigo: "11", nome: "CBT Jipe" },
    { codigo: "136", nome: "CHANA" },
    { codigo: "182", nome: "CHANGAN" },
    { codigo: "12", nome: "Chrysler" },
    { codigo: "13", nome: "Citroën" },
    { codigo: "14", nome: "Cross Lander" },
    { codigo: "241", nome: "D2D Motors" },
    { codigo: "15", nome: "Daewoo" },
    { codigo: "16", nome: "Daihatsu" },
    { codigo: "246", nome: "DFSK" },
    { codigo: "17", nome: "Dodge" },
    { codigo: "147", nome: "EFFA" },
    { codigo: "18", nome: "Engesa" },
    { codigo: "19", nome: "Envemo" },
    { codigo: "20", nome: "Ferrari" },
    { codigo: "249", nome: "FEVER" },
    { codigo: "21", nome: "Fiat" },
    { codigo: "149", nome: "Fibravan" },
    { codigo: "22", nome: "Ford" },
    { codigo: "190", nome: "FOTON" },
    { codigo: "170", nome: "Fyber" },
    { codigo: "254", nome: "GAC" },
    { codigo: "199", nome: "GEELY" },
    { codigo: "23", nome: "GM - Chevrolet" },
    { codigo: "153", nome: "GREAT WALL" },
    { codigo: "24", nome: "Gurgel" },
    { codigo: "240", nome: "GWM" },
    { codigo: "152", nome: "HAFEI" },
    { codigo: "214", nome: "HITECH ELECTRIC" },
    { codigo: "25", nome: "Honda" },
    { codigo: "26", nome: "Hyundai" },
    { codigo: "27", nome: "Isuzu" },
    { codigo: "208", nome: "IVECO" },
    { codigo: "177", nome: "JAC" },
    { codigo: "251", nome: "Jaecoo" },
    { codigo: "28", nome: "Jaguar" },
    { codigo: "29", nome: "Jeep" },
    { codigo: "154", nome: "JINBEI" },
    { codigo: "30", nome: "JPX" },
    { codigo: "31", nome: "Kia Motors" },
    { codigo: "32", nome: "Lada" },
    { codigo: "171", nome: "LAMBORGHINI" },
    { codigo: "33", nome: "Land Rover" },
    { codigo: "260", nome: "Leapmotor" },
    { codigo: "34", nome: "Lexus" },
    { codigo: "168", nome: "LIFAN" },
    { codigo: "127", nome: "LOBINI" },
    { codigo: "35", nome: "Lotus" },
    { codigo: "140", nome: "Mahindra" },
    { codigo: "36", nome: "Maserati" },
    { codigo: "37", nome: "Matra" },
    { codigo: "38", nome: "Mazda" },
    { codigo: "211", nome: "Mclaren" },
    { codigo: "39", nome: "Mercedes-Benz" },
    { codigo: "40", nome: "Mercury" },
    { codigo: "167", nome: "MG" },
    { codigo: "156", nome: "MINI" },
    { codigo: "41", nome: "Mitsubishi" },
    { codigo: "42", nome: "Miura" },
    { codigo: "250", nome: "NETA" },
    { codigo: "43", nome: "Nissan" },
    { codigo: "252", nome: "Omoda" },
    { codigo: "44", nome: "Peugeot" },
    { codigo: "45", nome: "Plymouth" },
    { codigo: "46", nome: "Pontiac" },
    { codigo: "47", nome: "Porsche" },
    { codigo: "185", nome: "RAM" },
    { codigo: "186", nome: "RELY" },
    { codigo: "48", nome: "Renault" },
    { codigo: "195", nome: "Rolls-Royce" },
    { codigo: "49", nome: "Rover" },
    { codigo: "50", nome: "Saab" },
    { codigo: "51", nome: "Saturn" },
    { codigo: "52", nome: "Seat" },
    { codigo: "247", nome: "SERES" },
    { codigo: "183", nome: "SHINERAY" },
    { codigo: "157", nome: "smart" },
    { codigo: "125", nome: "SSANGYONG" },
    { codigo: "54", nome: "Subaru" },
    { codigo: "55", nome: "Suzuki" },
    { codigo: "165", nome: "TAC" },
    { codigo: "56", nome: "Toyota" },
    { codigo: "57", nome: "Troller" },
    { codigo: "58", nome: "Volvo" },
    { codigo: "59", nome: "VW - VolksWagen" },
    { codigo: "163", nome: "Wake" },
    { codigo: "120", nome: "Walk" },
    { codigo: "253", nome: "ZEEKR" }
  ],
  motos: [
    { codigo: "60", nome: "ADLY" },
    { codigo: "61", nome: "AGRALE" },
    { codigo: "131", nome: "AMAZONAS" },
    { codigo: "62", nome: "APRILIA" },
    { codigo: "63", nome: "ATALA" },
    { codigo: "216", nome: "AVELLOZ" },
    { codigo: "64", nome: "BAJAJ" },
    { codigo: "205", nome: "BEE" },
    { codigo: "162", nome: "Benelli" },
    { codigo: "65", nome: "BETA" },
    { codigo: "66", nome: "BIMOTA" },
    { codigo: "67", nome: "BMW" },
    { codigo: "68", nome: "BRANDY" },
    { codigo: "130", nome: "BRAVA" },
    { codigo: "150", nome: "BRP" },
    { codigo: "117", nome: "BUELL" },
    { codigo: "155", nome: "BUENO" },
    { codigo: "212", nome: "BULL" },
    { codigo: "69", nome: "byCristo" },
    { codigo: "70", nome: "CAGIVA" },
    { codigo: "71", nome: "CALOI" },
    { codigo: "72", nome: "DAELIM" },
    { codigo: "145", nome: "DAFRA" },
    { codigo: "137", nome: "DAYANG" },
    { codigo: "142", nome: "DAYUN" },
    { codigo: "73", nome: "DERBI" },
    { codigo: "74", nome: "DUCATI" },
    { codigo: "75", nome: "EMME" },
    { codigo: "248", nome: "FEVER" },
    { codigo: "132", nome: "FOX" },
    { codigo: "209", nome: "FUSCO MOTOSEGURA" },
    { codigo: "128", nome: "FYM" },
    { codigo: "143", nome: "GARINNI" },
    { codigo: "76", nome: "GAS GAS" },
    { codigo: "133", nome: "GREEN" },
    { codigo: "138", nome: "HAOBAO" },
    { codigo: "203", nome: "HAOJUE" },
    { codigo: "77", nome: "HARLEY-DAVIDSON" },
    { codigo: "78", nome: "HARTFORD" },
    { codigo: "79", nome: "HERO" },
    { codigo: "261", nome: "Hisun" },
    { codigo: "80", nome: "HONDA" },
    { codigo: "81", nome: "HUSABERG" },
    { codigo: "82", nome: "HUSQVARNA" },
    { codigo: "202", nome: "INDIAN" },
    { codigo: "158", nome: "IROS" },
    { codigo: "141", nome: "JIAPENG VOLCANO" },
    { codigo: "174", nome: "JOHNNYPAG" },
    { codigo: "151", nome: "JONNY" },
    { codigo: "129", nome: "KAHENA" },
    { codigo: "118", nome: "KASINSKI" },
    { codigo: "85", nome: "KAWASAKI" },
    { codigo: "87", nome: "KTM" },
    { codigo: "204", nome: "KYMCO" },
    { codigo: "159", nome: "LANDUM" },
    { codigo: "88", nome: "L'AQUILA" },
    { codigo: "89", nome: "LAVRALE" },
    { codigo: "139", nome: "LERIVO" },
    { codigo: "258", nome: "LEVA" },
    { codigo: "178", nome: "LIFAN" },
    { codigo: "148", nome: "Lon-V" },
    { codigo: "175", nome: "MAGRÃO TRICICLOS" },
    { codigo: "146", nome: "Malaguti" },
    { codigo: "126", nome: "MIZA" },
    { codigo: "259", nome: "Mobílli" },
    { codigo: "90", nome: "MOTO GUZZI" },
    { codigo: "201", nome: "MOTOCAR" },
    { codigo: "255", nome: "MOTOMORINI" },
    { codigo: "200", nome: "MOTORINO" },
    { codigo: "160", nome: "MRX" },
    { codigo: "91", nome: "MV AGUSTA" },
    { codigo: "92", nome: "MVK" },
    { codigo: "239", nome: "NIU" },
    { codigo: "93", nome: "ORCA" },
    { codigo: "164", nome: "PEGASSI" },
    { codigo: "94", nome: "PEUGEOT" },
    { codigo: "95", nome: "PIAGGIO" },
    { codigo: "210", nome: "POLARIS" },
    { codigo: "173", nome: "REGAL RAPTOR" },
    { codigo: "198", nome: "RIGUETE" },
    { codigo: "192", nome: "Royal Enfield" },
    { codigo: "96", nome: "SANYANG" },
    { codigo: "262", nome: "SBM" },
    { codigo: "134", nome: "SHINERAY" },
    { codigo: "97", nome: "SIAMOTO" },
    { codigo: "98", nome: "SUNDOWN" },
    { codigo: "237", nome: "SUPER SOCO" },
    { codigo: "99", nome: "SUZUKI" },
    { codigo: "176", nome: "TARGOS" },
    { codigo: "187", nome: "TIGER" },
    { codigo: "119", nome: "TRAXX" },
    { codigo: "100", nome: "TRIUMPH" },
    { codigo: "244", nome: "Ventane Motors" },
    { codigo: "180", nome: "VENTO" },
    { codigo: "256", nome: "VESPA" },
    { codigo: "215", nome: "VOLTZ" },
    { codigo: "243", nome: "WATTS" },
    { codigo: "135", nome: "WUYANG" },
    { codigo: "101", nome: "YAMAHA" },
    { codigo: "242", nome: "ZONTES" }
  ],
  caminhoes: [
    { codigo: "102", nome: "AGRALE" },
    { codigo: "257", nome: "ARROW" },
    { codigo: "206", nome: "BEPOBUS" },
    { codigo: "103", nome: "CHEVROLET" },
    { codigo: "121", nome: "CICCOBUS" },
    { codigo: "197", nome: "DAF" },
    { codigo: "179", nome: "EFFA-JMC" },
    { codigo: "104", nome: "FIAT" },
    { codigo: "105", nome: "FORD" },
    { codigo: "191", nome: "FOTON" },
    { codigo: "106", nome: "GMC" },
    { codigo: "181", nome: "HYUNDAI" },
    { codigo: "122", nome: "IVECO" },
    { codigo: "188", nome: "JAC" },
    { codigo: "184", nome: "MAN" },
    { codigo: "108", nome: "MARCOPOLO" },
    { codigo: "196", nome: "MASCARELLO" },
    { codigo: "194", nome: "MAXIBUS" },
    { codigo: "109", nome: "MERCEDES-BENZ" },
    { codigo: "110", nome: "NAVISTAR" },
    { codigo: "111", nome: "NEOBUS" },
    { codigo: "112", nome: "PUMA-ALFA" },
    { codigo: "113", nome: "SAAB-SCANIA" },
    { codigo: "114", nome: "SCANIA" },
    { codigo: "193", nome: "SHACMAN" },
    { codigo: "166", nome: "SINOTRUK" },
    { codigo: "115", nome: "VOLKSWAGEN" },
    { codigo: "116", nome: "VOLVO" },
    { codigo: "144", nome: "WALKBUS" }
  ]
};

// Popular models fallback - used when API fails for specific brands
// Contains most searched models for major brands
import { Model } from './constants';

export const FALLBACK_MODELS: Record<string, Model[]> = {
  // VW - VolksWagen (codigo: 59)
  "59": [
    { codigo: 5940, nome: "Gol 1.0" },
    { codigo: 5941, nome: "Gol 1.6" },
    { codigo: 6756, nome: "Polo 1.0 TSI" },
    { codigo: 6757, nome: "Polo 1.4 TSI" },
    { codigo: 6673, nome: "T-Cross 1.0 TSI" },
    { codigo: 6674, nome: "T-Cross 1.4 TSI" },
    { codigo: 6826, nome: "Nivus 1.0 TSI" },
    { codigo: 6549, nome: "Virtus 1.0 TSI" },
    { codigo: 6550, nome: "Virtus 1.4 TSI" },
    { codigo: 6286, nome: "Jetta 1.4 TSI" },
    { codigo: 6287, nome: "Jetta 2.0 TSI" },
    { codigo: 6680, nome: "Taos 1.4 TSI" },
    { codigo: 6571, nome: "Tiguan 1.4 TSI" },
    { codigo: 6572, nome: "Tiguan 2.0 TSI" },
    { codigo: 6688, nome: "Amarok 2.0 TDI" },
    { codigo: 6689, nome: "Amarok 3.0 V6 TDI" },
    { codigo: 5585, nome: "Fox 1.0" },
    { codigo: 5586, nome: "Fox 1.6" },
    { codigo: 5665, nome: "Saveiro 1.6" },
    { codigo: 5503, nome: "Voyage 1.0" },
    { codigo: 5504, nome: "Voyage 1.6" }
  ],
  // FIAT (codigo: 21)
  "21": [
    { codigo: 5765, nome: "Argo 1.0" },
    { codigo: 5766, nome: "Argo 1.3" },
    { codigo: 5767, nome: "Argo 1.8" },
    { codigo: 7099, nome: "Cronos 1.0" },
    { codigo: 7100, nome: "Cronos 1.3" },
    { codigo: 7101, nome: "Cronos 1.8" },
    { codigo: 7355, nome: "Pulse 1.0 Turbo" },
    { codigo: 7356, nome: "Pulse 1.3 Turbo" },
    { codigo: 7400, nome: "Fastback 1.0 Turbo" },
    { codigo: 7401, nome: "Fastback 1.3 Turbo" },
    { codigo: 5801, nome: "Mobi 1.0" },
    { codigo: 6160, nome: "Strada 1.3" },
    { codigo: 6161, nome: "Strada 1.4" },
    { codigo: 6162, nome: "Strada 1.8" },
    { codigo: 5608, nome: "Toro 1.8" },
    { codigo: 5609, nome: "Toro 2.0 Diesel" },
    { codigo: 5350, nome: "Uno 1.0" },
    { codigo: 5351, nome: "Uno 1.4" }
  ],
  // GM - Chevrolet (codigo: 23)
  "23": [
    { codigo: 6408, nome: "Onix 1.0" },
    { codigo: 6409, nome: "Onix 1.0 Turbo" },
    { codigo: 6410, nome: "Onix Plus 1.0 Turbo" },
    { codigo: 6705, nome: "Tracker 1.0 Turbo" },
    { codigo: 6706, nome: "Tracker 1.2 Turbo" },
    { codigo: 6140, nome: "S10 2.5" },
    { codigo: 6141, nome: "S10 2.8 Diesel" },
    { codigo: 6142, nome: "Trailblazer 2.8 Diesel" },
    { codigo: 6280, nome: "Spin 1.8" },
    { codigo: 6350, nome: "Cruze 1.4 Turbo" },
    { codigo: 6805, nome: "Montana 1.2 Turbo" },
    { codigo: 5720, nome: "Cobalt 1.4" },
    { codigo: 5721, nome: "Cobalt 1.8" },
    { codigo: 5580, nome: "Prisma 1.0" },
    { codigo: 5581, nome: "Prisma 1.4" }
  ],
  // Toyota (codigo: 56)
  "56": [
    { codigo: 6255, nome: "Corolla 1.8" },
    { codigo: 6256, nome: "Corolla 2.0" },
    { codigo: 6257, nome: "Corolla Cross 1.8 Hybrid" },
    { codigo: 6258, nome: "Corolla Cross 2.0" },
    { codigo: 6420, nome: "Yaris 1.3" },
    { codigo: 6421, nome: "Yaris 1.5" },
    { codigo: 6422, nome: "Yaris Sedan 1.5" },
    { codigo: 6130, nome: "Hilux 2.7" },
    { codigo: 6131, nome: "Hilux 2.8 Diesel" },
    { codigo: 6132, nome: "SW4 2.7" },
    { codigo: 6133, nome: "SW4 2.8 Diesel" },
    { codigo: 6650, nome: "RAV4 2.5 Hybrid" },
    { codigo: 5980, nome: "Etios 1.3" },
    { codigo: 5981, nome: "Etios 1.5" }
  ],
  // Honda (codigo: 25)
  "25": [
    { codigo: 6180, nome: "Civic 1.5 Turbo" },
    { codigo: 6181, nome: "Civic 2.0" },
    { codigo: 6315, nome: "City 1.5" },
    { codigo: 6316, nome: "City Hatch 1.5" },
    { codigo: 6500, nome: "HR-V 1.5 Turbo" },
    { codigo: 6501, nome: "HR-V 1.8" },
    { codigo: 6390, nome: "CR-V 1.5 Turbo" },
    { codigo: 6391, nome: "CR-V 2.0 Hybrid" },
    { codigo: 6600, nome: "ZR-V 2.0 Hybrid" },
    { codigo: 5680, nome: "Fit 1.4" },
    { codigo: 5681, nome: "Fit 1.5" },
    { codigo: 5755, nome: "WR-V 1.5" }
  ],
  // Hyundai (codigo: 26)
  "26": [
    { codigo: 6220, nome: "HB20 1.0" },
    { codigo: 6221, nome: "HB20 1.0 Turbo" },
    { codigo: 6222, nome: "HB20 1.6" },
    { codigo: 6223, nome: "HB20S 1.0" },
    { codigo: 6224, nome: "HB20S 1.0 Turbo" },
    { codigo: 6460, nome: "Creta 1.0 Turbo" },
    { codigo: 6461, nome: "Creta 2.0" },
    { codigo: 6580, nome: "Tucson 1.6 Turbo" },
    { codigo: 6581, nome: "Tucson 2.0" },
    { codigo: 6750, nome: "Santa Fe 2.0 Turbo" },
    { codigo: 6751, nome: "Santa Fe 3.5 V6" }
  ],
  // Ford (codigo: 22)
  "22": [
    { codigo: 6800, nome: "Ranger 2.0 Diesel" },
    { codigo: 6801, nome: "Ranger 3.0 V6 Diesel" },
    { codigo: 6340, nome: "Territory 1.5 Turbo" },
    { codigo: 6341, nome: "Territory 2.0 Turbo" },
    { codigo: 5900, nome: "Ka 1.0" },
    { codigo: 5901, nome: "Ka 1.5" },
    { codigo: 5902, nome: "Ka Sedan 1.0" },
    { codigo: 5903, nome: "Ka Sedan 1.5" },
    { codigo: 6100, nome: "EcoSport 1.5" },
    { codigo: 6101, nome: "EcoSport 2.0" },
    { codigo: 5850, nome: "Fiesta 1.0" },
    { codigo: 5851, nome: "Fiesta 1.6" },
    { codigo: 6050, nome: "Focus 1.6" },
    { codigo: 6051, nome: "Focus 2.0" }
  ],
  // Renault (codigo: 48)
  "48": [
    { codigo: 6700, nome: "Kwid 1.0" },
    { codigo: 6710, nome: "Sandero 1.0" },
    { codigo: 6711, nome: "Sandero 1.6" },
    { codigo: 6720, nome: "Logan 1.0" },
    { codigo: 6721, nome: "Logan 1.6" },
    { codigo: 6730, nome: "Duster 1.6" },
    { codigo: 6731, nome: "Duster 2.0" },
    { codigo: 6740, nome: "Captur 1.3 Turbo" },
    { codigo: 6741, nome: "Captur 1.6" },
    { codigo: 6760, nome: "Oroch 1.6" },
    { codigo: 6761, nome: "Oroch 2.0" }
  ],
  // Jeep (codigo: 29)
  "29": [
    { codigo: 6850, nome: "Renegade 1.3 Turbo" },
    { codigo: 6851, nome: "Renegade 1.8" },
    { codigo: 6860, nome: "Compass 1.3 Turbo" },
    { codigo: 6861, nome: "Compass 2.0 Diesel" },
    { codigo: 6870, nome: "Commander 1.3 Turbo" },
    { codigo: 6871, nome: "Commander 2.0 Diesel" },
    { codigo: 6880, nome: "Wrangler 2.0 Turbo" },
    { codigo: 6890, nome: "Grand Cherokee 3.6 V6" }
  ],
  // Nissan (codigo: 43)
  "43": [
    { codigo: 6900, nome: "Kicks 1.6" },
    { codigo: 6910, nome: "Versa 1.6" },
    { codigo: 6920, nome: "Sentra 2.0" },
    { codigo: 6930, nome: "Frontier 2.3 Diesel" },
    { codigo: 6940, nome: "March 1.0" },
    { codigo: 6941, nome: "March 1.6" }
  ],
  // Mitsubishi (codigo: 41)
  "41": [
    { codigo: 6950, nome: "L200 Triton 2.4 Diesel" },
    { codigo: 6960, nome: "Outlander 2.0" },
    { codigo: 6961, nome: "Outlander 2.2 Diesel" },
    { codigo: 6970, nome: "Eclipse Cross 1.5 Turbo" },
    { codigo: 6980, nome: "Pajero Sport 2.4 Diesel" },
    { codigo: 6990, nome: "ASX 2.0" }
  ]
};
